apiVersion: v1
kind: ServiceAccount
metadata:
  name: httpbin
  namespace: httpbin
  labels:
    app.kubernetes.io/instance: httpbin
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: httpbin
  labels:
    app: httpbin
    app.kubernetes.io/instance: httpbin
    service: httpbin
    solo.io/service-scope: global
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8080
  selector:
    app: httpbin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  namespace: httpbin
  labels:
    app.kubernetes.io/instance: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
      version: v1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
    spec:
      serviceAccountName: httpbin
      containers:
        - name: httpbin
          image: mccutchen/go-httpbin:v2.14.1
          ports:
            - containerPort: 8080
          command:
            - /bin/go-httpbin
            - -port
            - "8080"
            - -max-duration
            - 600s
