apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster2-httpbin
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/huzlak/istio-ambient-argo-gitops
    targetRevision: main
    path: multicluster/manifests/httpbin
  destination:
    server: https://172.19.0.6:6443
    namespace: httpbin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
