apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster2-httpbin
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: REPO_URL
    targetRevision: TARGET_REVISION
    path: multicluster/manifests/httpbin
  destination:
    server: CLUSTER2_SERVER
    namespace: httpbin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
