apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster2-istio-base
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: default
  source:
    repoURL: us-docker.pkg.dev/soloio-img/istio-helm
    chart: base
    targetRevision: 1.28.4-solo
  destination:
    server: https://172.19.0.6:6443
    namespace: istio-system
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
        - .webhooks[]?.failurePolicy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
