apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster1-gloo-platform
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://storage.googleapis.com/gloo-platform/helm-charts
    chart: gloo-platform
    targetRevision: 2.12.0
    helm:
      values: |
        common:
          cluster: cluster1
        licensing:
          glooMeshCoreLicenseKey: eyJhZGRPbnMiOiIiLCJleHAiOjE5NjYzNDUwMzMsImlhdCI6MTY1MDk4NTAzMywiayI6IkFwU2NKZyIsImx0IjoidHJpYWwiLCJwcm9kdWN0IjoiZ2xvby1tZXNoLWdhdGV3YXkifQ.cVNIiCm57crZl2Ryaj24y_PtqjRmBWrRHnaNKcBYvcw
        glooMgmtServer:
          enabled: true
          serviceType: ClusterIP
          serviceOverrides:
            metadata:
              labels:
                solo.io/service-scope: global
          relay:
            pushRbac: true
        glooUi:
          enabled: true
        redis:
          deployment:
            enabled: true
        prometheus:
          enabled: true
        telemetryGateway:
          enabled: true
          service:
            type: ClusterIP
        telemetryCollector:
          enabled: true
  ignoreDifferences:
    - group: ""
      kind: Service
      name: gloo-telemetry-gateway
      jsonPointers:
        - /metadata/labels/solo.io~1service-scope
  destination:
    server: https://kubernetes.default.svc
    namespace: gloo-mesh
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
