apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: us-docker.pkg.dev/soloio-img/istio-helm
    chart: istiod
    targetRevision: 1.28.4-solo
    helm:
      values: |
        profile: ambient
        pilot:
          trustedZtunnelNamespace: kube-system
        meshConfig:
          trustDomain: CLUSTER_NAME
        global:
          multiCluster:
            clusterName: CLUSTER_NAME
          network: CLUSTER_NAME
        env:
          PILOT_ENABLE_IP_AUTOALLOCATE: "true"
          PILOT_ENABLE_ALPHA_GATEWAY_API: "true"
          PILOT_SKIP_VALIDATE_TRUST_DOMAIN: "true"
          DISABLE_LEGACY_MULTICLUSTER: "true"
        platforms:
          peering:
            enabled: true
        license:
          secretRef:
            name: solo-istio-license
            namespace: istio-system
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
