apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster2-eastwest-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/huzlak/istio-ambient-argo-gitops
    targetRevision: main
    path: multicluster-with-mgmt/manifests/eastwest/cluster2
  destination:
    server: https://172.19.0.6:6443
    namespace: istio-eastwest
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
