apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster2-gloo-platform-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://storage.googleapis.com/gloo-platform/helm-charts
    chart: gloo-platform-crds
    targetRevision: GLOO_PLATFORM_VERSION
    helm:
      values: |
        installEnterpriseCrds: false
  destination:
    server: https://172.19.0.6:6443
    namespace: gloo-mesh
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
